baseURL = "https://<Github-userid>.github.io/"
publishDir = "../mySite"

languageCode = "en-us"
title = "<Techtaste>"
theme = "hugo-min"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""


[params]
    author = "Chari"
    description = "Sample hugo site"
    githubUsername = "rchari66"
    accent = "royalblue"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "yaml", "toml", "java", "bash"]
    favicon = "img/logo.jpg"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2
[[menu.main]]
    url = "/categories/"
    name = "Categories"
    weight = 3

[[menu.main]]
    url = "/tags/"
    name = "tags"
    weight = 4

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 5


# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:youremail@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/rchari66/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/raghavendra-k-17528154/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/username/"
    name = "stack-overflow"
    weight = 5
